ci:
  autoupdate_commit_msg: "chore: [pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: end-of-file-fixer
        # exclude generated files
        exclude: ^validation/|\.dtd$|\.json$|\.xml$
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316" # frozen: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8 # frozen: v2.4.3
    hooks:
      - id: codespell
        files: ^.*\.(py|md|rst)$
        args: ["-w", "-L", "hist,gaus,merrors,SLAC,slac"]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "0ee178619d696787ca73d210cc191d720868c631" # frozen: v3.9.6
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]
        args: [--prose-wrap=always]

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa # frozen: v1.29.0
    hooks:
      - id: zizmor
        files: "^\\.github"
        args: [--persona=pedantic]
